"""Regression contracts for the PR review/fix automation.

These checks are intentionally structural. The workflow runs on GitHub, but
the failure modes they guard are local policy regressions: self-triggering
routine comments, stale post-merge fires, bot-authorized merges, and merges
with unresolved current review threads.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github/workflows/pr-agent.yml"
FIRE_ACTION = ROOT / ".github/actions/fire-routine/action.yml"
MERGE_ACTION = ROOT / ".github/actions/pr-merge-ready/action.yml"
ROUTINE_PROMPT = ROOT / "docs/pr-agent-routine-prompt.md"


def _read(path):
    return path.read_text(encoding="utf-8")


def test_review_events_are_collapsed_and_generated_feedback_is_ignored():
    workflow = _read(WORKFLOW)

    assert "cancel-in-progress: true" in workflow
    assert "<!-- pr-agent-generated -->" in workflow
    assert "Generated by [Claude Code]" in workflow
    assert "cancel-in-progress: false" not in workflow
    assert "--remove-label pr-agent-needs-human" in workflow
    assert workflow.count("uses: actions/checkout@v5") == workflow.count(
        "ref: ${{ github.event.repository.default_branch }}"
    )


def test_routine_fire_rechecks_live_pr_state_and_expected_head():
    action = _read(FIRE_ACTION)

    assert "--json state,headRefOid,headRepositoryOwner,headRepository" in action
    assert 'if [[ "${state}" != "OPEN" ]]' in action
    assert 'if [[ "${head_repo}" != "${REPO}" ]]' in action
    assert '"${current_head}" != "${EXPECTED_HEAD}"*' in action
    assert "Expected head: ${current_head}" in action
    assert "[pr-agent-review-fix:${PR}]" in action
    assert '"${prior_rounds}" -ge "${MAX_REVIEW_FIX_ROUNDS}"' in action
    assert "--add-label pr-agent-needs-human" in action


def test_only_humans_can_authorize_a_head_bound_merge():
    workflow = _read(WORKFLOW)

    human_actor_line = next(line for line in workflow.splitlines() if "HUMAN_MERGE_ACTORS:" in line)
    assert "jss367" in human_actor_line
    assert "bot" not in human_actor_line
    assert "merge-on-thumbsup:" not in workflow
    assert "merge-on-reaction:" not in workflow
    assert "startsWith(github.event.comment.body, '/merge ')" in workflow
    assert "approved-head: ${{ github.event.review.commit_id }}" in workflow
    assert "approved-head: ${{ steps.command.outputs.approved_head }}" in workflow


def test_merge_gate_requires_live_head_and_resolved_current_threads():
    action = _read(MERGE_ACTION)

    assert 'if [[ "$state" != "OPEN" ]]' in action
    assert 'if [[ "$head_sha" != "$APPROVED_HEAD"* ]]' in action
    assert "reviewThreads(first:100" in action
    assert ".isResolved == false and .isOutdated == false" in action
    assert 'if [[ "$unresolved" -gt 0 ]]' in action


def test_routine_contract_is_bounded_quiet_and_resolves_addressed_threads():
    prompt = _read(ROUTINE_PROMPT)

    assert "silent no-op: do not push and do not post a comment" in prompt
    assert "two such rounds already exist" in prompt
    assert "resolveReviewThread" in prompt
    assert "Do not blanket-resolve threads" in prompt
    assert "<!-- pr-agent-generated -->" in prompt
    assert "separate top-level success summary" in prompt
