"""Regression contracts for the PR review/fix automation.

These checks are intentionally structural. The workflow runs on GitHub, but
the failure modes they guard are local policy regressions: self-triggering
routine comments, stale post-merge fires, bot-authorized merges, and merges
with unresolved current review threads.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github/workflows/pr-agent.yml"
FIRE_ACTION = ROOT / ".github/actions/fire-routine/action.yml"
MERGE_ACTION = ROOT / ".github/actions/pr-merge-ready/action.yml"
ROUTINE_PROMPT = ROOT / "docs/pr-agent-routine-prompt.md"


def _read(path):
    return path.read_text(encoding="utf-8")


def test_review_events_are_collapsed_and_generated_feedback_is_ignored():
    workflow = _read(WORKFLOW)

    assert "cancel-in-progress: true" in workflow
    assert "<!-- pr-agent-generated -->" in workflow
    assert "Generated by [Claude Code]" in workflow
    assert "--remove-label pr-agent-needs-human" in workflow
    assert workflow.count("uses: actions/checkout@v5") == workflow.count(
        "ref: ${{ github.event.repository.default_branch }}"
    )


def test_concurrency_is_scoped_per_task_and_never_workflow_wide():
    workflow = _read(WORKFLOW)

    # A workflow-wide `pr-agent-<PR>` group with cancel-in-progress: true
    # would let an ignored generated comment cancel an in-flight `/merge`
    # or approval-driven auto-merge run for the same PR. Keep the
    # concurrency block per-job instead.
    stripped = "\n".join(line for line in workflow.splitlines() if not line.lstrip().startswith("#"))
    assert "\nconcurrency:\n" not in stripped

    # Review-fix firers share a per-PR group so newer reviews collapse
    # earlier ones without touching merge or CI-fix work.
    review_group_issue = "group: pr-agent-review-fix-${{ github.event.issue.number }}"
    review_group_pr = "group: pr-agent-review-fix-${{ github.event.pull_request.number }}"
    assert workflow.count(review_group_issue) == 2  # activate + fix-comment-feedback
    assert workflow.count(review_group_pr) == 2  # fix-comments + codex-review

    # Merge jobs get their own per-PR group so they don't race with —
    # or get cancelled by — the review-fix lane.
    assert "group: pr-agent-merge-${{ github.event.pull_request.number }}" in workflow
    assert "group: pr-agent-merge-${{ github.event.issue.number }}" in workflow

    # fix-ci derives the PR number from `workflow_run.pull_requests[0]`
    # so unrelated PRs sharing a default-branch SHA don't cancel each
    # other's CI-repair runs.
    assert (
        "group: pr-agent-ci-fix-${{ github.event.workflow_run.pull_requests[0].number "
        "|| github.event.workflow_run.head_sha }}"
    ) in workflow

    # resolve-conflicts is a single global scan; group it as such.
    assert "group: pr-agent-resolve-conflicts" in workflow

    # Guard against a review-fix job regressing to `cancel-in-progress: false`,
    # which would preserve a queue of stale reviews. Every review-fix,
    # CI-fix, and conflict-scan group must collapse; only merge groups
    # keep `false` so an in-flight authorization is not cancelled by a
    # newer approval event that also passes the gate.
    collapse_groups = (
        review_group_issue,
        review_group_pr,
        "group: pr-agent-ci-fix-",
        "group: pr-agent-resolve-conflicts",
    )
    for group_prefix in collapse_groups:
        idx = workflow.find(group_prefix)
        while idx != -1:
            end_of_line = workflow.find("\n", idx)
            next_line_start = end_of_line + 1
            next_line_end = workflow.find("\n", next_line_start)
            next_line = workflow[next_line_start:next_line_end]
            assert "cancel-in-progress: true" in next_line, (
                f"{group_prefix!r} must set cancel-in-progress: true, got {next_line!r}"
            )
            idx = workflow.find(group_prefix, next_line_end)


def test_merge_command_does_not_double_fire_the_review_fix_routine():
    workflow = _read(WORKFLOW)

    # `/merge <sha>` on a claude-agent PR is a merge command handled by
    # `merge-on-command`. If `fix-comment-feedback` also fired on it, the
    # routine could push a new head and invalidate the human's SHA-bound
    # merge authorization before auto-merge is enabled.
    assert "!startsWith(github.event.comment.body, '/merge ')" in workflow


def test_routine_fire_rechecks_live_pr_state_and_expected_head():
    action = _read(FIRE_ACTION)

    assert "--json state,headRefOid,headRepositoryOwner,headRepository" in action
    assert 'if [[ "${state}" != "OPEN" ]]' in action
    assert 'if [[ "${head_repo}" != "${REPO}" ]]' in action
    assert '"${current_head}" != "${EXPECTED_HEAD}"*' in action
    assert "Expected head: ${current_head}" in action
    assert "[pr-agent-review-fix:${PR}]" in action
    assert '"${prior_rounds}" -ge "${MAX_REVIEW_FIX_ROUNDS}"' in action
    assert "--add-label pr-agent-needs-human" in action


def test_only_humans_can_authorize_a_head_bound_merge():
    workflow = _read(WORKFLOW)

    human_actor_line = next(line for line in workflow.splitlines() if "HUMAN_MERGE_ACTORS:" in line)
    assert "jss367" in human_actor_line
    assert "bot" not in human_actor_line
    assert "merge-on-thumbsup:" not in workflow
    assert "merge-on-reaction:" not in workflow
    assert "startsWith(github.event.comment.body, '/merge ')" in workflow
    assert "approved-head: ${{ github.event.review.commit_id }}" in workflow
    assert "approved-head: ${{ steps.command.outputs.approved_head }}" in workflow


def test_merge_gate_requires_live_head_and_resolved_current_threads():
    action = _read(MERGE_ACTION)

    assert 'if [[ "$state" != "OPEN" ]]' in action
    assert 'if [[ "$head_sha" != "$APPROVED_HEAD"* ]]' in action
    assert "reviewThreads(first:100" in action
    assert ".isResolved == false and .isOutdated == false" in action
    assert 'if [[ "$unresolved" -gt 0 ]]' in action


def test_routine_contract_is_bounded_quiet_and_resolves_addressed_threads():
    prompt = _read(ROUTINE_PROMPT)

    assert "silent no-op: do not push and do not post a comment" in prompt
    assert "two such rounds already exist" in prompt
    assert "resolveReviewThread" in prompt
    assert "Do not blanket-resolve threads" in prompt
    assert "<!-- pr-agent-generated -->" in prompt
    assert "separate top-level success summary" in prompt
