"""Regression contracts for the PR review/fix automation.

These checks are intentionally structural. The workflow runs on GitHub, but
the failure modes they guard are local policy regressions: self-triggering
routine comments, stale post-merge fires, bot-authorized merges, and merges
with unresolved current review threads.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github/workflows/pr-agent.yml"
FIRE_ACTION = ROOT / ".github/actions/fire-routine/action.yml"
MERGE_ACTION = ROOT / ".github/actions/pr-merge-ready/action.yml"
ROUTINE_PROMPT = ROOT / "docs/pr-agent-routine-prompt.md"


def _read(path):
    return path.read_text(encoding="utf-8")


def test_review_events_are_collapsed_and_generated_feedback_is_ignored():
    workflow = _read(WORKFLOW)

    assert "cancel-in-progress: true" in workflow
    assert "<!-- pr-agent-generated -->" in workflow
    assert "Generated by [Claude Code]" in workflow
    assert "--remove-label pr-agent-needs-human" in workflow
    assert workflow.count("uses: actions/checkout@v5") == workflow.count(
        "ref: ${{ github.event.repository.default_branch }}"
    )


def test_concurrency_is_scoped_per_task_and_never_workflow_wide():
    workflow = _read(WORKFLOW)

    # A workflow-wide `pr-agent-<PR>` group with cancel-in-progress: true
    # would let an ignored generated comment cancel an in-flight `/merge`
    # or approval-driven auto-merge run for the same PR. Keep the
    # concurrency block per-job instead.
    stripped = "\n".join(line for line in workflow.splitlines() if not line.lstrip().startswith("#"))
    assert "\nconcurrency:\n" not in stripped

    # Review-fix firers share a per-PR group so newer reviews collapse
    # earlier ones without touching merge or CI-fix work.
    review_group_issue = "group: pr-agent-review-fix-${{ github.event.issue.number }}"
    review_group_pr = "group: pr-agent-review-fix-${{ github.event.pull_request.number }}"
    assert workflow.count(review_group_issue) == 2  # activate + fix-comment-feedback
    assert workflow.count(review_group_pr) == 2  # fix-comments + codex-review

    # Merge jobs get their own per-PR group so they don't race with —
    # or get cancelled by — the review-fix lane.
    assert "group: pr-agent-merge-${{ github.event.pull_request.number }}" in workflow
    assert "group: pr-agent-merge-${{ github.event.issue.number }}" in workflow

    # `disable-automerge-on-head-change` is deliberately NOT in the merge
    # group: GitHub Actions keeps only one pending job per group even with
    # `cancel-in-progress: false`, so a shared group would let an
    # authorized-at-workflow-level merge event silently displace this
    # pending disarm and leave auto-merge armed against a stale head. Keep
    # it in its own per-PR group.
    assert "group: pr-agent-disable-merge-${{ github.event.pull_request.number }}" in workflow

    # fix-ci derives the PR number from `workflow_run.pull_requests[0]`
    # so unrelated PRs sharing a default-branch SHA don't cancel each
    # other's CI-repair runs.
    assert (
        "group: pr-agent-ci-fix-${{ github.event.workflow_run.pull_requests[0].number "
        "|| github.event.workflow_run.head_sha }}"
    ) in workflow

    # resolve-conflicts is a single global scan; group it as such.
    assert "group: pr-agent-resolve-conflicts" in workflow

    # Guard against a review-fix job regressing to `cancel-in-progress: false`,
    # which would preserve a queue of stale reviews. Every review-fix,
    # CI-fix, and conflict-scan group must collapse; only merge groups
    # keep `false` so an in-flight authorization is not cancelled by a
    # newer approval event that also passes the gate.
    collapse_groups = (
        review_group_issue,
        review_group_pr,
        "group: pr-agent-ci-fix-",
        "group: pr-agent-resolve-conflicts",
        "group: pr-agent-disable-merge-",
    )
    for group_prefix in collapse_groups:
        idx = workflow.find(group_prefix)
        while idx != -1:
            end_of_line = workflow.find("\n", idx)
            next_line_start = end_of_line + 1
            next_line_end = workflow.find("\n", next_line_start)
            next_line = workflow[next_line_start:next_line_end]
            assert "cancel-in-progress: true" in next_line, (
                f"{group_prefix!r} must set cancel-in-progress: true, got {next_line!r}"
            )
            idx = workflow.find(group_prefix, next_line_end)


def test_merge_command_does_not_double_fire_the_review_fix_routine():
    workflow = _read(WORKFLOW)

    # `/merge <sha>` on a claude-agent PR is a merge command handled by
    # `merge-on-command`. If `fix-comment-feedback` also fired on it, the
    # routine could push a new head and invalidate the human's SHA-bound
    # merge authorization before auto-merge is enabled.
    assert "!startsWith(github.event.comment.body, '/merge ')" in workflow


def test_ci_fix_binds_to_failing_run_head_not_live_pr_head():
    workflow = _read(WORKFLOW)

    # When Tests for commit A completes after the PR has advanced to
    # commit B, passing the live PR head B as expected-head would let the
    # routine edit B while diagnosing A's failure logs. The stale-head
    # skip and the expected-head passthrough must both key on
    # `github.event.workflow_run.head_sha`, not the current PR head.
    assert "WORKFLOW_RUN_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}" in workflow
    assert 'if [[ "$live_head" != "$WORKFLOW_RUN_HEAD_SHA" ]]' in workflow
    assert 'echo "head_sha=$WORKFLOW_RUN_HEAD_SHA"' in workflow


def test_routine_fire_rechecks_live_pr_state_and_expected_head():
    action = _read(FIRE_ACTION)

    assert "--json state,headRefOid,headRepositoryOwner,headRepository" in action
    assert 'if [[ "${state}" != "OPEN" ]]' in action
    assert 'if [[ "${head_repo}" != "${REPO}" ]]' in action
    assert '"${current_head}" != "${EXPECTED_HEAD}"*' in action
    assert "Expected head: ${current_head}" in action
    assert "[pr-agent-review-fix:${PR}]" in action
    assert '"${prior_rounds}" -ge "${MAX_REVIEW_FIX_ROUNDS}"' in action
    assert "--add-label pr-agent-needs-human" in action


def test_only_humans_can_authorize_a_head_bound_merge():
    workflow = _read(WORKFLOW)

    human_actor_line = next(line for line in workflow.splitlines() if "HUMAN_MERGE_ACTORS:" in line)
    assert "jss367" in human_actor_line
    assert "bot" not in human_actor_line
    assert "merge-on-thumbsup:" not in workflow
    assert "merge-on-reaction:" not in workflow
    assert "startsWith(github.event.comment.body, '/merge ')" in workflow
    assert "approved-head: ${{ github.event.review.commit_id }}" in workflow
    assert "approved-head: ${{ steps.command.outputs.approved_head }}" in workflow


def test_merge_gate_requires_live_head_and_resolved_current_threads():
    action = _read(MERGE_ACTION)

    assert 'if [[ "$state" != "OPEN" ]]' in action
    assert 'if [[ "$head_sha" != "$APPROVED_HEAD"* ]]' in action
    assert "reviewThreads(first:100" in action
    assert ".isResolved == false and .isOutdated == false" in action
    assert 'if [[ "$unresolved" -gt 0 ]]' in action


def test_routine_contract_is_bounded_quiet_and_resolves_addressed_threads():
    prompt = _read(ROUTINE_PROMPT)

    assert "silent no-op: do not push and do not post a comment" in prompt
    assert "two such rounds already exist" in prompt
    assert "resolveReviewThread" in prompt
    assert "Do not blanket-resolve threads" in prompt
    assert "<!-- pr-agent-generated -->" in prompt
    assert "separate top-level success summary" in prompt


def test_disable_automerge_handler_cannot_be_displaced_by_merge_lane():
    workflow = _read(WORKFLOW)

    # GitHub Actions keeps only one pending job per concurrency group; a
    # newer arrival replaces the pending one even when `cancel-in-progress`
    # is false. If `disable-automerge-on-head-change` shared the
    # `pr-agent-merge-<PR>` group with the merge-arming jobs, a subsequent
    # merge event (an approval, or a `/merge <sha>` comment that passes the
    # workflow-level `author_association` gate but later fails the
    # step-level `HUMAN_MERGE_ACTORS` check) would silently replace the
    # pending disarm off the merge group's single pending slot — cancelling
    # the safeguard entirely and leaving auto-merge armed against a stale
    # head. The disarm must therefore live in its own per-PR group.
    disarm_idx = workflow.find("disable-automerge-on-head-change:")
    merge_approval_idx = workflow.find("\n  merge-on-approval:")
    assert disarm_idx != -1 and merge_approval_idx > disarm_idx
    disarm_block = workflow[disarm_idx:merge_approval_idx]

    assert (
        "group: pr-agent-disable-merge-${{ github.event.pull_request.number }}"
        in disarm_block
    )
    # And the shared merge group must NOT be reused inside the disarm block,
    # or the displacement race would reopen.
    assert (
        "group: pr-agent-merge-${{ github.event.pull_request.number }}"
        not in disarm_block
    )
    # Idempotent disarm — `cancel-in-progress: true` collapses two nearby
    # pushes into a single disarm run without leaving stale queued work.
    assert "cancel-in-progress: true" in disarm_block


def test_synchronize_disables_auto_merge_so_authorization_binds_to_head():
    workflow = _read(WORKFLOW)

    # `gh pr merge --auto --match-head-commit` checks the SHA at arm time,
    # not at eventual merge time. A commit pushed after auto-merge is armed
    # would otherwise merge without a fresh `/merge <new-sha>` or approval.
    # Guard this by disabling auto-merge on every synchronize event so the
    # next merge requires re-authorization against the new head.
    assert "pull_request:\n    types: [synchronize]" in workflow
    assert "disable-automerge-on-head-change:" in workflow
    assert "github.event.action == 'synchronize'" in workflow
    assert "gh pr merge \"$PR\" --repo \"$REPO\" --disable-auto" in workflow


def test_human_claude_fix_overrides_routine_round_cap():
    workflow = _read(WORKFLOW)
    prompt = _read(ROUTINE_PROMPT)

    # The activate job (fired by a human `/claude-fix`) intentionally leaves
    # `max-review-fix-rounds` at zero so the workflow-level cap does not
    # apply, but the routine also caps at two prior rounds and would
    # otherwise silently no-op the documented human override. The workflow
    # signals the override to the routine via a distinct task kind
    # (`address-human-fix`) on the first line of the payload — never via a
    # text field that could be interpolated from an untrusted body region.
    activate_idx = workflow.find("activate:")
    fix_comment_idx = workflow.find("fix-comment-feedback:")
    assert activate_idx != -1 and fix_comment_idx > activate_idx
    activate_block = workflow[activate_idx:fix_comment_idx]
    assert "address-human-fix" in activate_block

    # Only the activate job may emit `address-human-fix`; every other
    # firer stays on the capped task kinds. Count the ternary-quoted
    # literal so this catches an accidental copy into another payload
    # block without being tripped by design-comment references to the
    # string.
    assert workflow.count("'address-human-fix'") == 1

    # The routine prompt must document the new task kind and use it as the
    # override signal.
    assert "address-human-fix" in prompt
    assert "skip the round cap" in prompt

    # The routine prompt must NOT still key its override off a text field
    # that a bot could inject through `Review body` or `Comment body`.
    assert "If the payload includes `Human override: true`" not in prompt
    assert "payload includes `Human override" not in prompt


def test_human_override_signal_cannot_be_injected_through_untrusted_feedback():
    """A bot posting `Human override: true` in a comment or review body
    must not bypass the round cap. The trust boundary is the task kind on
    the first line of the payload, which only the workflow can set."""

    workflow = _read(WORKFLOW)
    prompt = _read(ROUTINE_PROMPT)

    # The workflow must never write `Human override: true` (in any casing)
    # into a payload — the field is retired in favor of the task kind so
    # there is no ambiguous string a bot could echo back through
    # `Comment body:` or `Review body:`.
    assert "Human override:" not in workflow

    # The routine prompt must explicitly warn against honoring a
    # `Human override` string inside an untrusted body region, and must
    # anchor the override to the task kind.
    assert "task kind on the very first line is `address-human-fix`" in prompt
    lowered = prompt.lower()
    assert "not honor" in lowered and "human override" in lowered

    # And the four routes that carry untrusted body text (address-review,
    # address-human-fix, address-comment, address-codex-review) must all
    # be listed as sharing the same flow, so the "task kind gate" rule
    # applies uniformly.
    assert "`address-review`, `address-human-fix`, `address-comment`, `address-codex-review`" in prompt


def test_bots_cannot_grant_human_override_or_reset_escalation_via_activate():
    workflow = _read(WORKFLOW)

    activate_idx = workflow.find("activate:")
    fix_comment_idx = workflow.find("fix-comment-feedback:")
    activate_block = workflow[activate_idx:fix_comment_idx]

    # The activate condition admits `chatgpt-codex-connector[bot]`, so the
    # trusted `address-human-fix` task kind must be gated on the commenter's
    # author_association rather than emitted unconditionally. Otherwise a
    # bot's /claude-fix comment would bypass both the workflow-level and
    # routine-level two-round caps and could drive automated repair
    # indefinitely.
    task_line = next(
        line for line in activate_block.splitlines()
        if "Task:" in line and "address-human-fix" in line
    )
    assert "steps.live.outputs.is_human" in task_line, (
        f"address-human-fix task kind must be gated on the is_human step "
        f"output; got {task_line!r}"
    )
    # And the alternate branch of the gate must fall back to the capped
    # `address-review` kind for bots.
    assert "address-review" in task_line, (
        f"Non-human /claude-fix must fall back to the capped `address-review` "
        f"task kind; got {task_line!r}"
    )

    # The workflow-level cap (via `max-review-fix-rounds`) must also flip
    # from disabled (0) to enabled (>=1) for non-human invokers so both
    # cap layers apply.
    max_rounds_line = next(
        line for line in activate_block.splitlines() if "max-review-fix-rounds:" in line
    )
    assert "steps.live.outputs.is_human" in max_rounds_line, (
        f"max-review-fix-rounds must be gated on is_human; got {max_rounds_line!r}"
    )

    # The pr-agent-needs-human escalation label must not be cleared by a
    # bot's /claude-fix, or an already-escalated PR could be silently
    # reset back into the automated lane. The label-clear must sit inside
    # a shell guard checking the is_human step output (surfaced as
    # $IS_HUMAN in the step env).
    label_step_idx = activate_block.find("- name: Add agent label")
    checkout_idx = activate_block.find("- uses: actions/checkout", label_step_idx)
    label_step = activate_block[label_step_idx:checkout_idx]
    assert "--remove-label pr-agent-needs-human" in label_step
    assert 'IS_HUMAN: ${{ steps.live.outputs.is_human }}' in label_step
    assert 'if [[ "$IS_HUMAN" == "true" ]]; then' in label_step
    # The remove-label call must appear after the guard opens.
    guard_open = label_step.find('if [[ "$IS_HUMAN" == "true" ]]; then')
    remove_pos = label_step.find("--remove-label pr-agent-needs-human")
    assert guard_open != -1 and remove_pos > guard_open

    # The Check live PR state step must derive is_human from the commenter's
    # author_association (OWNER/COLLABORATOR), the same trust anchor the
    # activate `if:` uses for human maintainers.
    check_step = activate_block.split("- name: Add agent label")[0]
    assert 'AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}' in check_step
    assert '"$AUTHOR_ASSOCIATION" == "OWNER"' in check_step
    assert '"$AUTHOR_ASSOCIATION" == "COLLABORATOR"' in check_step
    assert 'echo "is_human=true" >> "$GITHUB_OUTPUT"' in check_step
    assert 'echo "is_human=false" >> "$GITHUB_OUTPUT"' in check_step
